### PR TITLE
Add a minor multithreading optimization

### PR DESCRIPTION
**Pull request by behroozkhorashadi**

### CODE REVIEW

**Comment by vinc3m1** [comment]
@swankjesse is this what you wanted?

**Comment by swankjesse** [comment]
Yeah, thumbs up. I think it'd also be powerful to let the caller lookup the Validator instance and call validate themselves. That way if I'm doing say a Retrofit adapter where the type being validated is always `Taco` I only need to do the map lookup once.

**Comment by behroozkhorashadi** [comment]
@tyvsmith Can you take a quick look at this?

**Comment by tyvsmith** [comment]
@behroozkhorashadi The synchronization fix looks good to me. What are you thoughts on @swankjesse's request. I think that's a good idea we should do, but as a separate PR.

**Comment by behroozkhorashadi** [comment]
@tyvsmith So the only issue with @swankjesse 's request is that because of RAVE's multi-library support, validation of a single object can span across multiple Validator instances, which means caching a single instance in that case doesn't win you much. It can also lead to instability since Validators will throw runtime exceptions if given an unhandled object. On the other hand I can see the advantage of having the ability to do this in the simple case. Let me think about it a bit and see what I can come up with.

**Pull request merged**
