### PR TITLE
Ignore AutoValue's toBuilder() methods

### PR DESCRIPTION
**Pull request by hzsweers**
These are fulfilled by AutoValue and *not* something we should be validating as it's just wasteful allocation.

This works by checking if the type is annotated with `@AutoValue` and if the method name is `toBuilder`. Fairly simple and doesn't depend directly on AutoValue. I think it's ok for us to be mindful here since it's all implementation detail at compile-time and not leaking dependencies into the public API. There's precedent for this pattern in autovalue/error-prone/etc as well

### CODE REVIEW

**Comment by hzsweers** [comment]
Let me know how you think we should test this. As mentioned in #17, I'm not totally sure how the test structure here works

**Comment by naturalwarren** [comment]
We have the `ExclusionStrategy` API to do this and don't need to make a special exception for `AutoValue`.

If you're generating models using some kind of source generation tool like [JavaPoet](https://github.com/square/javapoet) I'd recommend creating a custom `ExclusionStrategy` at that time.

**Comment by hzsweers** [comment]
The `ExclusionStrategy` API is not flexible enough for this without inducing an excessive amount of boilerplate. It's not really solvable by code gen since they'd all need to be manually hooked up and imposes quite a bit of unnecessary boilerplate on the user.

an `@Excluded` annotation would be a nice orthogonal improvement that code gen could nicely cover, but is still a burden for the average user. This is a case where rave validation is actually wanted 0% of the time, and we can handle it in an API-invisible way to reduce burden on consumers.

**Comment by naturalwarren** [comment]
> an @Excluded annotation would be a nice orthogonal improvement that code gen could nicely cover, but is still a burden for the average user. This is a case where rave validation is actually wanted 0% of the time, and we can handle it in an API-invisible way to reduce burden on consumers.

I agree an `@Excluded` annotation would be a good improvement. However, I think we should solve the problem of having a good API for exclusion instead of making one-off exceptions in our processor for a specific value class generation library like [AutoValue](https://github.com/google/auto/tree/master/value). 

@behroozkhorashi thoughts?

**Comment by hzsweers** [comment]
> instead of making one-off exceptions in our processor for a specific value class generation library like AutoValue.

I don't agree with the implication here that this is a bad, as that's just your opinion. AutoValue accounts for several other conditions, from guava and dagger to eclipse. Flexible handling has been born out of those changes too (like how immutable classes will recognize `copyOf` methods).

**Comment by naturalwarren** [comment]
> AutoValue accounts for several other conditions, from guava and dagger to eclipse.

There's nothing in `auto/value` that accounts for conditions in Dagger.

Regarding Eclipse, `auto/value` works around bugs in Eclipse's implementation of annotation processing. This makes sense since they want to ensure their library can work with that IDE. They haven't built optimizations into `auto/value` if you're using Eclipse.

Guava's an interesting case that supports the idea of accounting for an additional "condition" but I'd also point out that they're both Google libraries and are intended to play well with one another.

My thoughts are the `@Excluded` annotation is a better path forward. In addition to improving the use of this library with AutoValue (which is the intent of this PR) it solves a larger issue with the library that we should fix.

**Comment by hzsweers** [comment]
Maybe I'm mixing up with AutoFactory, but changes have definitely been made in AutoValue with at least an indirect nod toward Dagger.

> My thoughts are the @Excluded annotation is a better path forward.

Can you flesh out what that would look like more?

**Comment by hzsweers** [comment]
@kageiit and I discussed and we have another proposal:

A new annotation that sits on the validator factory class. Shape is something like 

```java
@RaveExclude(annotated = Class<? extends Annotation> [], methodNames = String [])
```

Then use is something like

```
@RaveExclude(annotated = AutoValue.class, methodNames = {"toBuilder", "toString"})
public final class RaveValidatorFactory implements ValidatorFactory {
  // Whatever
}
```

This keeps it at a relatively high scope (not per-method or per-model, but rather per-module and thus alleviates a lot of the boilerplate concerns mentioned), while also still dynamic and up to the user.

**Comment by naturalwarren** [comment]
I'm a fan of this approach, nice work. Looking forward to PR.

**Pull request closed without merging**
